language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "boilermaker-test";' -U postgres
deploy:
  api_key:
    secure: JUI0zZQtjKAhETbptGSXMRjUsRXK9XXzWigabhnC4qvKyoebchJ9O/8WYVuIar4SDDiBbWjPFEt6bnjgte+0ba3W+srE6GXKKPi0ypoEg3n8OGSu8nMH1Nr8IcRhLVsxYuzwD3VXH1rsTflkdfSf6DwgpvkHE2VioNWaCw1L/AYPNOOgEV4GjlsEPVd3gr1WQs+pRQsfm0yXl7yoPKKpAaGp5AzpSINkejrsnVpHHgl/m6hc0pEft2EP30CP09C0/xaNnc7SBNXSWfvyQ0FUCURIcdGT8KssBzzJ94k6rKNXDm2ZqcPLRJltVxwXVFkecw58gSPOwcgcEcY2iM+OKqVEXxuQkSEjEcYj8z9MVgCzwn2uGIbRzJV/hDtwNrdmkce1zQTwe+CJYfUWPMPFJK63fF1eFVhu8IjOLlCSoYVCWRhbpq4XONaEnbTBeCOrMC0yrkt729rwQ3rUBtf/uvGZ1LZyuCziUv1ZWoGiO7nVUNC2dOoFOlpq8g6t34BXnpQftvp2TD4ODTOx2699e+GVgmbaf3D2hX2DaiVZHUD/cOVcDR8OPJ1fGrZZrpZUGrmvz9wN9QFQI1ouwrB/aRgb8U2lMcAn8XXpmNAMvkBGYuCeKv+T7bsDoA1aLWm/ai5lyiitUn3wU3V+VlwZFIV8iovryL1uX7b9Mggi91g=
